# Generated by Django 4.0.1 on 2023-11-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
