# Generated by Django 4.0.1 on 2023-11-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='livromodel',
            name='categoria',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='livromodel',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livromodel',
            name='quantidade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livromodel',
            name='validade',
            field=models.DateField(null=True),
        ),
    ]
